DROP TABLE IF EXISTS DEPARTMENTS;
CREATE TABLE DEPARTMENTS (DEPT_NO VARCHAR(10),
	DEPT_NAME VARCHAR(50));
	
DROP TABLE IF EXISTS DEPT_MANAGER;
CREATE TABLE DEPT_MANAGER (DEPT_NO VARCHAR(10),
EMP_NO INT, FROM_DATE DATE,TO_DATE DATE	);

CREATE TABLE EMPLOYEES (EMP_NO SERIAL PRIMARY KEY,
BIRTH_DATE DATE, FIRST_NAME VARCHAR(50), LAST_NAME VARCHAR(50),
GENDER VARCHAR(10),HIRE_DATE DATE);

SELECT * FROM DEPT_MANAGER;

SELECT * FROM EMPLOYEES;
SELECT * FROM SALARIES;
CREATE TABLE SALARIES (EMP_NO INT, SALARY FLOAT, FROM_DATE DATE,
					  TO_DATE DATE);

DROP TABLE IF EXISTS TITLES;
CREATE TABLE TITLES (EMP_NO INT , TITLE VARCHAR(50),
					FROM_DATE DATE, TO_DATE DATE);
					
CREATE TABLE DEPT_EMP (EMP_NO INT, DEPT_NO VARCHAR(10), 
					  FROM_DATE DATE, TO_DATE DATE);
					  
/* 1. List the following details of each employee: 
employee number, last name, first name, gender, and salary.*/

SELECT E.EMP_NO AS "EMPLOYEE NUMBER",
E.LAST_NAME AS "LAST NAME",
E.FIRST_NAME AS "FIRST NAME",
E.GENDER AS "GENDER", S.SALARY AS "SALARY"

FROM EMPLOYEES E
LEFT JOIN SALARIES S
ON E.EMP_NO=S.EMP_NO
ORDER BY E.EMP_NO;

--List employees who were hired in 1986.

SELECT FIRST_NAME, LAST_NAME, 
EXTRACT(YEAR FROM HIRE_DATE) AS HIRE_YEAR
FROM EMPLOYEES
WHERE EXTRACT(YEAR FROM HIRE_DATE) = 1986;

/* List the manager of each department with the following 
information: department number, department name, the manager's 
employee number, last name, first name, and start and end 
employment dates.*/

SELECT D.DEPT_NO AS "DEPARTMENT NUMBER", 
D.DEPT_NAME AS "DEPARTMENT NAME", DM.EMP_NO AS 
"MANAGER EMPLOYEE NUMBER", 
E.LAST_NAME AS "LAST NAME",
E.FIRST_NAME AS "FIRST NAME",
DE.FROM_DATE AS "START DATE",
DE.TO_DATE AS "END DATE"

FROM DEPARTMENTS D

RIGHT JOIN DEPT_MANAGER DM
ON D.DEPT_NO = DM.DEPT_NO

LEFT JOIN EMPLOYEES E
ON DM.EMP_NO = E.EMP_NO

LEFT JOIN DEPT_EMP DE
ON DM.EMP_NO = DE.EMP_NO

ORDER BY "DEPARTMENT NUMBER", "DEPARTMENT NAME",
"MANAGER EMPLOYEE NUMBER";


SELECT * FROM DEPARTMENTS;
SELECT * FROM DEPT_MANAGER;
SELECT COUNT (*) FROM EMPLOYEES;
SELECT COUNT(*) FROM (SELECT DISTINCT EMP_NO FROM EMPLOYEES) AS temp;
SELECT COUNT(*) FROM (SELECT DISTINCT EMP_NO FROM DEPT_EMP) AS temp;

SELECT COUNT (*) FROM DEPT_EMP;
SELECT * FROM EMPLOYEES;
SELECT * FROM DEPT_EMP;

/* List the department of each employee with the following 
information: employee number, last name, first name, and 
department name.*/

SELECT E.EMP_NO AS "EMPLOYEE NUMBER",
E.LAST_NAME AS "LAST NAME",
E.FIRST_NAME AS "FIRST NAME",
D.DEPT_NAME AS "DEPARTMENT NAME"

FROM EMPLOYEES E
LEFT JOIN DEPT_EMP DE
ON E.EMP_NO = DE.EMP_NO

LEFT JOIN DEPARTMENTS D
ON DE.DEPT_NO = D.DEPT_NO;

/*List all employees whose first name is "Hercules" and 
last names begin with "B."*/

SELECT FIRST_NAME AS "FIRST NAME",
LAST_NAME AS "LAST NAME"
FROM EMPLOYEES
WHERE FIRST_NAME = 'Hercules' AND LAST_NAME LIKE 'B%';

/*List all employees in the Sales department, including 
their employee number, last name, first name, and department name.*/

SELECT E.EMP_NO AS "EMPLOYEE NUMBER",
E.LAST_NAME AS "LAST NAME",
E.FIRST_NAME AS "FIRST NAME",
D.DEPT_NAME AS "DEPARTMENT NAME"

FROM EMPLOYEES E
LEFT JOIN DEPT_EMP DE ON E.EMP_NO = DE.EMP_NO
LEFT JOIN DEPARTMENTS D ON DE.DEPT_NO = D.DEPT_NO

WHERE D.DEPT_NAME = 'Sales';

/*List all employees in the Sales and Development departments, 
including their employee number, last name, first name, and 
department name.*/

SELECT E.EMP_NO AS "EMPLOYEE NUMBER",
E.LAST_NAME AS "LAST NAME",
E.FIRST_NAME AS "FIRST NAME",
D.DEPT_NAME AS "DEPARTMENT NAME"

FROM EMPLOYEES E
LEFT JOIN DEPT_EMP DE ON E.EMP_NO = DE.EMP_NO
LEFT JOIN DEPARTMENTS D ON DE.DEPT_NO = D.DEPT_NO

WHERE D.DEPT_NAME IN ('Sales','Development');

/*In descending order, list the frequency count of employee 
last names, i.e., how many employees share each last name.*/

SELECT LAST_NAME, COUNT(LAST_NAME)
FROM EMPLOYEES
GROUP BY LAST_NAME;

